export const MEDICATION_MASTER_CATALOG = [
  {
    name: "Metformin",
    genericName: "Metformin Hydrochloride",
    category: "Antidiabetic",
    commonDosages: ["500mg", "850mg", "1000mg"],
    commonFrequencies: ["Once daily", "Twice daily", "With meals"],
    unit: "tablet",
  },
  {
    name: "Glipizide",
    genericName: "Glipizide",
    category: "Antidiabetic",
    commonDosages: ["5mg", "10mg"],
    commonFrequencies: ["Once daily", "Twice daily"],
    unit: "tablet",
  },
  {
    name: "Insulin",
    genericName: "Insulin",
    category: "Antidiabetic",
    commonDosages: ["10U", "20U", "30U"],
    commonFrequencies: ["Once daily", "Twice daily", "With meals"],
    unit: "unit",
  },
  {
    name: "Lisinopril",
    genericName: "Lisinopril",
    category: "Antihypertensive",
    commonDosages: ["5mg", "10mg", "20mg", "40mg"],
    commonFrequencies: ["Once daily"],
    unit: "tablet",
  },
  {
    name: "Amlodipine",
    genericName: "Amlodipine Besylate",
    category: "Antihypertensive",
    commonDosages: ["2.5mg", "5mg", "10mg"],
    commonFrequencies: ["Once daily"],
    unit: "tablet",
  },
  {
    name: "Losartan",
    genericName: "Losartan Potassium",
    category: "Antihypertensive",
    commonDosages: ["25mg", "50mg", "100mg"],
    commonFrequencies: ["Once daily", "Twice daily"],
    unit: "tablet",
  },
  {
    name: "Paracetamol",
    genericName: "Acetaminophen",
    category: "Analgesic",
    commonDosages: ["500mg", "650mg", "1000mg"],
    commonFrequencies: ["As needed", "Every 4-6 hours", "Every 6-8 hours"],
    unit: "tablet",
  },
  {
    name: "Ibuprofen",
    genericName: "Ibuprofen",
    category: "Analgesic",
    commonDosages: ["200mg", "400mg", "600mg", "800mg"],
    commonFrequencies: ["As needed", "Every 6-8 hours", "With food"],
    unit: "tablet",
  },
  {
    name: "Atorvastatin",
    genericName: "Atorvastatin Calcium",
    category: "Cardiovascular",
    commonDosages: ["10mg", "20mg", "40mg", "80mg"],
    commonFrequencies: ["Once daily", "At bedtime"],
    unit: "tablet",
  },
  {
    name: "Aspirin",
    genericName: "Acetylsalicylic Acid",
    category: "Cardiovascular",
    commonDosages: ["75mg", "81mg", "100mg", "325mg"],
    commonFrequencies: ["Once daily", "As needed"],
    unit: "tablet",
  },
];

export const BLOOD_GROUPS = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

export const RELATIONSHIPS = [
  "Self",
  "Mother",
  "Father",
  "Child",
  "Spouse",
  "Sibling",
  "Grandparent",
  "Other",
];
